apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  template:
    spec:
      containers:
        - name: springboot
          volumeMounts:
            - name: spring-env
              mountPath: /app/.env
      volumes:
        - name: spring-env
          configMap:
            name: spring-env
