apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: springboot
    newName: registry.gitlab.com/s12-final/s12p31b206/springboot
    newTag: prod-0  # prod Jenkins에서 덮어쓰기
