import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className="bg-white transition-all duration-300 dark:bg-gray-700 text-gray-800 dark:text-gray-200 antialiased">
        {children}
      </body>
    </html>
  )
}
