spring:
  config:
    import: "optional:configserver:"
  application:
    name: nobasebattle

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_CONNECT_NAME}?authSource=${MONGO_AUTH}
      database: ${MONGO_DATABASE}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKETNAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}

openai:
  api:
    key: ${OPENAI_KEY}
    url: https://api.openai.com/v1/chat/completions

logging:
  file:
    name: ${LOGGING_DIR}
  level:
    root: INFO